distance_lens_array = 95.0
distance_detector_array = 2.0
array_path = '../lenses/raytrix_array.toml'

[lens]
focal_length_s = 100.0
focal_length_t = 100.0
center_s = 0.0
center_t = 0.0
radius_s = 10.0
radius_t = 10.0

[detector]
ns = 2400
nt = 2400
ds = 5.5e-3
dt = 5.5e-3
offset_s = 0.0
offset_t = 0.0
