array_path = "../lenses/shi_array.toml"
distance_detector_array = 0.308
distance_lens_array = 100.0

[detector]
ds = 0.005499999970197678
dt = 0.005499999970197678
ns = 2400
nt = 2400
offset_s = 0.0
offset_t = 0.0

[lens]
center_s = 0.0
center_t = 0.0
focal_length_s = 50.0
focal_length_t = 50.0
radius_s = 12.5
radius_t = 12.5
