distance_detector_lens = 32.0

[lens]
center_s = 3.0
center_t = -5.2
radius_s = 4.0
radius_t = 5.2
focal_length_s = 12.0
focal_length_t = 24.0

[detector]
ns = 1024
nt = 2048
ds = 1.0
dt = 2.0
offset_s = 0.0
offset_t = 1.0
