[object]
data = './dots.fld'
config = 'geometries/dots_over.toml'

[[camera]]
name = 'shi plenoptic 1.0 camera'
config = 'cameras/shi.toml'
position = { x = 0.0, y = 0.0, z = -100.0 }
data = 'shi.png'

