[object]
data = './torch.fld'
config = 'geometries/100mm3_opaque.toml'

[[camera]]
name = 'main_camera'
config = 'cameras/test_simple.toml'
position = { x = 0.0, y = 0.0, z = -500.0 }
data = 'test.png'

