[object]
data = "../test_volume.fld"
config = "test_volume.toml"

[object.box_constraints]
min = 0.0

[object.sparsifying]
type = 'abs'
weight = 2.0

[object.edge_preserving]
type = 'fair'
weight = 3.0
delta = 2.0

[[camera]]
name = "focal0"
config = "cameras/test_focal.toml"
position = { x = 0.0, y = 0.0, z = -500.0 }
data = "test0.png"

[[camera]]
name = "focal1"
config = "cameras/test_focal.toml"
data = "test1.fld"
[camera.position]
x = 50.0
y = 60.0
z = 12.0

