[package]
name = 'lightfield'
version = '0.0.1'
authors = ['Madison McGaffin <greyhill@gmailcom>']

[lib]
name = 'lightfield'
path = 'rs/lib.rs'
crate-type = ['rlib']

[dependencies.num]
version = '0.1.32'

