[package]

name = 'lightfield'
version = '0.0.1'
authors = ['Madison McGaffin <greyhill@gmail.com>']

[lib]
name = 'lightfield'
path = 'src/lib.rs'
crate-type = ['rlib', 'dylib']

[dependencies.scoped-pool]
version = '0.1.9'

